name: Run AQAvit

on:
  workflow_dispatch: # Allows the job to be manually triggered

jobs:
  run_aqa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [sanity, extended]
        suite: [functional, openjdk, system, perf]
        include:
          - target: special  
            suite: functional

    steps:
    # Install Java to be tested (you could alternatively build your binary here).
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Run AQA Tests - ${{ matrix.target }}.${{ matrix.suite }}
      uses: adoptium/run-aqa@v2
      with: 
        version: '11'
        jdksource: 'install-jdk'
        build_list: ${{ matrix.suite }}
        target: _${{ matrix.target }}.${{ matrix.suite }}
